#!/bin/python3

import math
import os
import random
import re
import sys

def solve(meal_cost, tip_percent, tax_percent):
    
    tip = meal_cost*(tip_percent/100)
    tax = meal_cost*(tax_percent/100)
    totcost = meal_cost + tip + tax
    return round(totcost)




meal_cost = float(input())

tip_percent = int(input())

tax_percent = int(input())

print(solve(meal_cost, tip_percent, tax_percent))
