#!/bin/python3

import math
import os
import random
import re
import sys

n = int(input())

if n%2 == 1:
    print("Weird")
elif(n >=2 and n<=5):
    if(n%2 == 0):
        print("Not Weird")
    else:
        print("Weird")
elif (n >=6 and n <= 20):
    if(n%2 == 0):
        print("Weird")
    else:
        print("Not Weird")
elif(n >=20):
    if(n%2 == 0):
        print("Not Weird")
    else:
        print("Weird")
